# Файл railway.yaml

# Определение службы для WebSocket сервера
services:
  websocket-server:
    # Указание образа Docker, который будет использоваться для службы
    image: railway/python:3.9

    # Команда, которая будет запускать ваш WebSocket сервер
    command: python main.py

    # Порт, на котором WebSocket сервер будет слушать входящие соединения
    # Убедитесь, что этот порт соответствует порту, на котором ваш сервер настроен слушать входящие соединения WebSocket
    env:
      - PORT: 7865

    # Объем ресурсов (опционально)
    # Эти параметры могут быть настроены в зависимости от требований вашего приложения
    plan: hobby
    concurrency: 1
    memory: 512MB